server: 
  port: 9090

spring: 
  datasource: 
    url: jdbc:oracle:thin:@61.78.121.242:8877:xe
    driver-class-name: oracle.jdbc.driver.OracleDriver
    username: bjscar
    password: bjscar
    #connection pool설정
    hikari:
      minimum-idle: 10
      maximum-pool-size: 50
      auto-commit: false
      connection-test-query: select 1 from dual
      pool-name: bspool
 #jpa환경설정하기
  jpa:
    generate-ddl: true
    show-sql: true
    database: oracle    
    database-platform: org.hibernate.dialect.Oracle9Dialect    
#    hibernate:
#      ddl-auto: create         

#mvc패턴으로 jsp페이지 연결하기
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
#mybatis
mybatis:
  config-location: classpath:mybatis-config.xml 
  mapper-locations: /mapper/**/*.xml
#kakao
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id:  c092a856fb0ff2740a4131083dd48690
            redirect-uri: http://localhost:8080/login/oauth2/code/kakao
            client-authentication-method: POST
            authorization-grant-type: authorization_code
            scope: profile_nickname,profile_image,account_email
            client-name: Kakao
        provider:
          kakao:
            authorization_uri: https://kauth.kakao.com/oauth/authorize
            token_uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user_name_attribute: id      
    
      
      
      
      
      
    